### ISSUE TITLE
강의 초기화 안내 문구 typo

### ISSUE THREAD

**Issue by bekker** [wafflestudio/snutt-android#9]
비문 수정

`강좌를(스페이스 두개)원래 상태로 초기화하시겠습니까`
->
`강좌를 원래 상태로 초기화하시겠습니까?`

**Comment by bekker** [comment]
![screenshot_2017-11-23-01-32-06](https://user-images.githubusercontent.com/4366401/33138765-a5c3662e-cfee-11e7-9b96-a07135440a05.png)

**Comment by makesource** [comment]
수정하였습니다.
v1.0.5 에서 확인해주세요~
